# Generated by Django 4.0 on 2021-12-24 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('availdate', models.DateField(db_column='availDate')),
            ],
            options={
                'db_table': 'availability',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_collation='utf8mb4_0900_ai_ci', max_length=16)),
            ],
            options={
                'db_table': 'role',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('description', models.CharField(blank=True, max_length=2045, null=True)),
                ('start_date', models.DateField()),
            ],
            options={
                'db_table': 'task',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('idteam', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=2048)),
            ],
            options={
                'db_table': 'team',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16)),
                ('last_name', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=32)),
                ('phone_num', models.IntegerField(blank=True, null=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('state', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TaskHasTeam',
            fields=[
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Controller.task')),
            ],
            options={
                'db_table': 'task_has_team',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TaskHasUser',
            fields=[
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Controller.task')),
            ],
            options={
                'db_table': 'task_has_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserHasTeam',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Controller.user')),
            ],
            options={
                'db_table': 'user_has_team',
                'managed': False,
            },
        ),
    ]
