# Generated by Django 4.0 on 2021-12-24 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('availdate', models.DateField(db_column='availDate')),
            ],
            options={
                'db_table': 'availability',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_collation='utf8mb4_0900_ai_ci', max_length=16)),
            ],
            options={
                'db_table': 'role',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16)),
                ('last_name', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=32)),
                ('phone_num', models.IntegerField(blank=True, null=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('state', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
